# Generated by Django 5.2.5 on 2025-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('UPI_QR', 'UPI QR'), ('WALLET', 'Wallet'), ('NET_BANKING', 'Net Banking')], max_length=20),
        ),
    ]
