# Generated by Django 5.2.5 on 2025-08-12 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_add_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='cart_user_or_session_required',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('session_id__isnull', True)), models.Q(('user__isnull', True), ('session_id__isnull', False)), _connector='OR'), name='cart_user_or_session_required'),
        ),
    ]
