# Generated by Django 5.2.5 on 2025-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_update_payment_method_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI_INTENT', 'UPI Intent'), ('UPI_COLLECT', 'UPI Collect'), ('UPI_QR', 'UPI QR'), ('CARD', 'Card'), ('TOKEN', 'Token'), ('NET_BANKING', 'Net Banking')], max_length=20),
        ),
    ]
