# Generated by Django 5.2.5 on 2025-10-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_id__isnull', False), models.Q(('transaction_id', ''), _negated=True)), fields=('transaction_id',), name='unique_non_empty_transaction_id'),
        ),
    ]
