# Generated by Django 5.2.5 on 2025-08-12 12:00

from django.db import migrations, models

def user_profile_picture_path(instance, filename):
    return f"profile_pictures/user_{instance.mobile_number}/{filename}"

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to=user_profile_picture_path),
        ),
    ]