# Generated by Django 5.2.5 on 2025-08-12 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, help_text='10-digit Indian alternate mobile number', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits starting with 6, 7, 8, or 9', regex='^[6-9]\\d{9}$')]),
        ),
    ]