# Generated by Django 5.2.5 on 2025-10-17 03:18

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_add_alternate_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to=user.models.user_profile_picture_path),
        ),
    ]
