# Generated by Django 5.2.5 on 2025-08-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurentMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('is_veg', models.BooleanField(default=False)),
                ('default_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.variant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.product')),
                ('restaurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.restaurententity')),
            ],
        ),
    ]
