# Generated by Django 5.2.5 on 2025-10-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('restaurent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurentmenu',
            options={'verbose_name': 'Restaurant Menu Item', 'verbose_name_plural': 'Restaurant Menu Items'},
        ),
        migrations.AlterUniqueTogether(
            name='restaurentmenu',
            unique_together={('restaurent', 'product')},
        ),
    ]
